<?php
/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
include_once $GLOBALS['THRIFT_ROOT'].'/packages/ThriftTest/ThriftTest_types.php';

$GLOBALS['ThriftTest_CONSTANTS'] = array();

$GLOBALS['ThriftTest_CONSTANTS']['myNumberz'] = 1;

?>
